config/routes.rb
Rails.application.routes.draw do
  resources :chunks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chunk.rb
class Chunk < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chunks_controller.rb
class ChunksController < ApplicationController
  before_action :set_chunk, only: [:show, :edit, :update, :destroy]

  # GET /chunks
  # GET /chunks.json
  def index
    @chunks = Chunk.all
  end

  # GET /chunks/1
  # GET /chunks/1.json
  def show
  end

  # GET /chunks/new
  def new
    @chunk = Chunk.new
  end

  # GET /chunks/1/edit
  def edit
  end

  # POST /chunks
  # POST /chunks.json
  def create
    @chunk = Chunk.new(chunk_params)

    respond_to do |format|
      if @chunk.save
        format.html { redirect_to @chunk, notice: 'Chunk was successfully created.' }
        format.json { render :show, status: :created, location: @chunk }
      else
        format.html { render :new }
        format.json { render json: @chunk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chunks/1
  # PATCH/PUT /chunks/1.json
  def update
    respond_to do |format|
      if @chunk.update(chunk_params)
        format.html { redirect_to @chunk, notice: 'Chunk was successfully updated.' }
        format.json { render :show, status: :ok, location: @chunk }
      else
        format.html { render :edit }
        format.json { render json: @chunk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chunks/1
  # DELETE /chunks/1.json
  def destroy
    @chunk.destroy
    respond_to do |format|
      format.html { redirect_to chunks_url, notice: 'Chunk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chunk
      @chunk = Chunk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chunk_params
      params.require(:chunk).permit(:user_id, :title, :code, :lang, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chunks_helper.rb
module ChunksHelper
end

app/views/chunks/_form.html.slim
= form_with(model: chunk, local: true) do |form|
  - if chunk.errors.any?
    #error_explanation
      h2
        = pluralize(chunk.errors.count, "error")
        |  prohibited this chunk from being saved:
      ul
        - chunk.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :user_id
    = form.number_field :user_id
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :code
    = form.text_field :code
  .field
    = form.label :lang
    = form.text_field :lang
  .field
    = form.label :desc
    = form.text_field :desc
  .actions
    = form.submit

app/views/chunks/edit.html.slim
h1
  | Editing Chunk
= render 'form', chunk: @chunk
= link_to 'Show', @chunk
|  | 
= link_to 'Back', chunks_path

app/views/chunks/index.html.slim
.row.justify-content-center.pt-4
  p#notice
    = notice
  = link_to 'New Chunk', new_chunk_path
.row.justify-content-center
  = render partial: 'parts/index_card', collection: @chunks, as: 'chunk'

app/views/chunks/new.html.slim
h1
  | New Chunk
= render 'form', chunk: @chunk
= link_to 'Back', chunks_path

app/views/chunks/show.html.slim
p#notice
  = notice
p
  strong
    | User:
  = @chunk.user_id
p
  strong
    | Title:
  = @chunk.title
p
  strong
    | Code:
  = @chunk.code
p
  strong
    | Lang:
  = @chunk.lang
p
  strong
    | Desc:
  = @chunk.desc
= link_to 'Edit', edit_chunk_path(@chunk)
|  | 
= link_to 'Back', chunks_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Codechunk
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    / bootstrap css
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"

    / highlight.js
    link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dark.min.css"
    script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js"
    javascript:
      hljs.initHighlightingOnLoad();
  body
    nav.navbar.navbar-light.bg-info
      a.navbar-brand.text-light href="./" CodeChunk

    .container-fluid
      = yield
    
    / bootstrap javascript
    script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"
    script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"

app/views/parts/_index_card.html.slim
.card.chunk.col-7.my-2.px-0
  / .card-header.bg-info
  .card-body.p-2
    .header.mb-2
      = image_tag 'face_icon/avataaars_1.png', class: 'user_icon'
      span.user_name.font-weight-bold
        | ジョン
      small.user_id.ml-1 
        | @john
    .card-pre.hljs.text-light
      .pre-code-header
        span.file-name.font-weight-bold style="color: #e6e1dc;"
          | container-up.sh
        span.badge.badge-pill.text-light.lang-badge style="margin: 0 1em; background-color: #d2b51c;"
          = chunk.lang
      pre.hljs.text-light.m-0
        code class="hljs #{chunk.lang.downcase()}"
          = chunk.code
    p.mt-1.mb-0
      = chunk.desc
  .card-footer.align-light
    span
      | 投稿：
      = chunk.created_at.strftime("%m/%d(%u) %H:%M")
    span
      = link_to '削除', chunk, method: :delete, data: { confirm: 'Are you sure?' }